INSERT INTO Genres(id,name) VALUES (16,'Animation');
INSERT INTO Genres(id,name) VALUES (35,'Comedy');
INSERT INTO Genres(id,name) VALUES (10751,'Family');
INSERT INTO Genres(id,name) VALUES (12,'Adventure');
INSERT INTO Genres(id,name) VALUES (14,'Fantasy');
INSERT INTO Genres(id,name) VALUES (10749,'Romance');
INSERT INTO Genres(id,name) VALUES (18,'Drama');
INSERT INTO Genres(id,name) VALUES (28,'Action');
INSERT INTO Genres(id,name) VALUES (80,'Crime');
INSERT INTO Genres(id,name) VALUES (53,'Thriller');
INSERT INTO Genres(id,name) VALUES (27,'Horror');
INSERT INTO Genres(id,name) VALUES (36,'History');
INSERT INTO Genres(id,name) VALUES (878,'Science Fiction');
INSERT INTO Genres(id,name) VALUES (9648,'Mystery');
INSERT INTO Genres(id,name) VALUES (10752,'War');
INSERT INTO Genres(id,name) VALUES (10769,'Foreign');
INSERT INTO Genres(id,name) VALUES (10402,'Music');
INSERT INTO Genres(id,name) VALUES (99,'Documentary');
INSERT INTO Genres(id,name) VALUES (37,'Western');
INSERT INTO Genres(id,name) VALUES (10770,'TV Movie');
